rootProject.name = "gs-vertx"
include("utilities")
include("gs-rest-service")
include("gs-consuming-rest")
include("gs-uploading-files")
include("gs-messaging-redis")
include("gs-actuator-service")
include("gs-managing-transactions")

include("vertx-in-action:chapter01")
include("vertx-in-action:chapter02")
include("vertx-in-action:chapter03")
include("vertx-in-action:chapter04")
include("vertx-in-action:chapter05")
include("vertx-in-action:chapter06")

include("vertx-in-action:part2-steps-challenge:public-api")
include("vertx-in-action:part2-steps-challenge:user-profile-service")
include("vertx-in-action:part2-steps-challenge:activity-service")
include("vertx-in-action:part2-steps-challenge:user-webapp")
include("vertx-in-action:part2-steps-challenge:ingestion-service")
include("vertx-in-action:part2-steps-challenge:congrats-service")
include("vertx-in-action:part2-steps-challenge:event-stats-service")
include("vertx-in-action:part2-steps-challenge:dashboard-webapp")
