/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 *
 * Detailed information about configuring a multi-project build in Gradle can be found
 * in the user manual at https://docs.gradle.org/7.4.2/userguide/multi_project_builds.html
 */

rootProject.name = "gs-vertx"
include("utilities")
include("gs-rest-service")
include("gs-consuming-rest")
include("gs-uploading-files")
include("gs-messaging-redis")
include("gs-actuator-service")
include("gs-managing-transactions")

include("vertx-in-action:chapter01")
include("vertx-in-action:chapter02")
include("vertx-in-action:chapter03")
