version: "3.8"

services:
  postgres:
    image: "postgres:15.1"
    container_name: "gs-managing-transactions"
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=gs-managing-transactions"
      - "POSTGRES_PASSWORD=gs-managing-transactions"
      - "POSTGRES_DB=gs-managing-transactions"
    networks:
      - gs-managing-transactions-local

networks:
  gs-managing-transactions-local:
    name: "gs-managing-transactions-local"